runtime: go118

env_variables:
  BOT_TOKEN: $BOT_TOKEN
  FILES_CHANNEL_ID: $FILES_CHANNEL_ID
  GOOGLEAPIS_CREDENTIALS: $GOOGLEAPIS_CREDENTIALS
  LOG_CHANNEL: $LOG_CHANNEL
  MONGODB_DATABASE_NAME: $MONGODB_DATABASE_NAME
  MONGODB_URI: $MONGODB_URI
