runtime: go118

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 0
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1

env_variables:
  BOT_TOKEN: $BOT_TOKEN
  FILES_CHANNEL_ID: $FILES_CHANNEL_ID
  GOOGLEAPIS_CREDENTIALS: $GOOGLEAPIS_CREDENTIALS
  LOG_CHANNEL: $LOG_CHANNEL
  MONGODB_DATABASE_NAME: $MONGODB_DATABASE_NAME
  MONGODB_URI: $MONGODB_URI
  HOST: $HOST
